server:
  port: 8082
security:
  oauth2:
    client:
      authorization-code:
        client-id: baidu
        client-secret: baidu
        grant-type: authorization_code
        user-authorization-uri: http://authorization-server:8080/oauth/authorize
        access-token-uri: http://authorization-server:8080/oauth/token
        pre-established-redirect-uri: http://localhost:8082/authorized
        use-current-uri: false
        scope: read
      client-credentials:
        client-id: baidu
        client-secret: baidu
        grant-type: client_credentials
        access-token-uri: http://authorization-server:8080/oauth/token
        scope: read
      password:
        client-id: baidu
        client-secret: baidu
        grant-type: password
        access-token-uri: http://authorization-server:8080/oauth/token
        scope: read